import { DEFAULT_QUIZ } from './_seed.js';
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
export function authorized(request,env){const key=request.headers.get('X-Admin-Key')||new URL(request.url).searchParams.get('admin')||'';return Boolean(env.ADMIN_KEY)&&key===env.ADMIN_KEY}
export async function ensureDb(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS state (id INTEGER PRIMARY KEY, json TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, name TEXT NOT NULL, mime TEXT NOT NULL, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();const row=await env.DB.prepare('SELECT id FROM state WHERE id=1').first();if(!row){await env.DB.prepare('INSERT INTO state (id,json) VALUES (1,?)').bind(JSON.stringify(DEFAULT_QUIZ)).run()}}
export async function readQuiz(env){await ensureDb(env);const row=await env.DB.prepare('SELECT json, updated_at FROM state WHERE id=1').first();return {quiz:JSON.parse(row.json),updatedAt:row.updated_at}}
export async function writeQuiz(env,quiz){await ensureDb(env);await env.DB.prepare(`UPDATE state SET json=?, updated_at=CURRENT_TIMESTAMP WHERE id=1`).bind(JSON.stringify(quiz)).run()}
export function validateQuiz(q){if(!q||typeof q!=='object')return'Neplatný JSON';if(!Array.isArray(q.rounds)||q.rounds.length!==5)return'Kvíz musí mít přesně 5 kol';for(const [ri,r] of q.rounds.entries()){if(!Array.isArray(r.topics)||r.topics.length!==2)return`Kolo ${ri+1} musí mít přesně 2 témata`;for(const [ti,t] of r.topics.entries()){if(!Array.isArray(t.questions)||t.questions.length!==5)return`Téma ${ri+1}.${ti+1} musí mít přesně 5 otázek`}}return null}
export function abToB64(ab){const bytes=new Uint8Array(ab);let out='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+chunk)));return btoa(out)}
export function b64ToBytes(s){const bin=atob(s);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
